title: Linh Nguyen # your name (or website title) here
logo: "/images/IMG_2443.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Uber Data Scientist
  <br><br>
  Duke Economics PhD
  <br><br>
  <a href="https://www.linkedin.com/in/linhnguyen91/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
